/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package frcdatasetcolab;

import io.javalin.Javalin;
import io.javalin.util.FileUtil;
import io.javalin.http.UploadedFile;


public class App {
    public static void main(String[] args) {
        Javalin app = Javalin.create(config -> {
            config.plugins.enableCors(cors -> {
                cors.add(corsConfig -> {
                    //replacement for enableCorsForAllOrigins()
                    corsConfig.anyHost();
                });
            });
        })
            .get("/", ctx -> ctx.result("Hello World"))
            .start(7070);
        /* 
        Javalin.create(config -> {
            config.plugins.enableCors(cors -> {
                cors.add(it -> {
                    it.anyHost();
                });
            });
        });
        
        app.options("/upload", ctx -> {
            ctx.header("Access-Control-Allow-Origin", "*");
            ctx.header("Access-Control-Allow-Methods", "POST");
            //ßSuperTokens.setRelevantHeadersForOptionsAPI(ctx);
            ctx.result("success");
        });
        */
        app.post("/upload", ctx -> {
            ctx.uploadedFiles("files").forEach(uploadedFile ->
                FileUtil.streamToFile(uploadedFile.content(), "upload/" + uploadedFile.filename()));
        });
    }
    
}

/* 
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
*/