"use client";
import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { CurrentNavbar } from "@/components/navbar/currentNavbar";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Dataset Colab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <div className="flex min-h-screen w-full flex-col">
        <CurrentNavbar />
        {children}
      </div>
    </html>
  );
}
