"use client";
import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import { cn } from "@/lib/utils";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { cookies } from "next/headers";

import { LoginDialogMobile } from "@/components/auth/loginDialogMobile";
import { LogoutUser } from "@/components/auth/logoutUser";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from ".//firebase/config";

import { GetUser } from "./firebase/GetUser";

import { CircleUser, Menu, Package2, Search } from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";

import {
  Command,
  CommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandSeparator,
  CommandShortcut,
} from "@/components/ui/command";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Dataset Colab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const [open, setOpen] = React.useState(false);

  React.useEffect(() => {
    const down = (e: KeyboardEvent) => {
      if (e.key === "k" && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        setOpen((open) => !open);
      }
    };
    document.addEventListener("keydown", down);
    return () => document.removeEventListener("keydown", down);
  }, []);
  /*
  const cookieStore = cookies()
  let sessionTokenCookie:any = cookieStore.get('user')
  let user:any;
  if (!(sessionTokenCookie === undefined)) {
    user = sessionTokenCookie.value;
  }
  let signedIn = false;
  if (user!=undefined) {
    if (user === 'true') {
      signedIn = true;
    }
  }
  */
  //console.log(valueOf(GetUser));

  /*
  return (
    <html lang="en">
      <nav className="bg-white">
        <div className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
          <div className="relative flex h-16 items-center justify-between">
            <div className="absolute inset-y-0 left-0 flex items-center sm:hidden">
              <button
                type="button"
                className="relative inline-flex items-center justify-center rounded-md p-2 text-gray-800 hover:bg-gray-200 hover:text-gray-800 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
                aria-controls="mobile-menu"
                aria-expanded="false"
              ></button>
            </div>
            <div className="flex flex-1 items-center justify-between sm:items-stretch sm:justify-start">
              <div className="flex flex-shrink-0 items-center">
                <h1 className="pr-3" style={{ whiteSpace: "nowrap" }}>
                  Dataset Colab
                </h1>
                <Button asChild>
                  <Link href="/login">Login</Link>
                </Button>
              </div>
              <div className="hidden sm:flex sm:ml-auto">
                <div className="flex space-x-4"></div>
                <div className="flex space-x-4 ml-auto">
                  <div className="flex w-full max-w-sm items-center space-x-2">
                    <Input placeholder="Search..." />
                    <Button type="submit">Search</Button>
                  </div>
                </div>
                <div className="ml-4"></div>
              </div>
              {GetUser != undefined ? <LogoutUser /> : (<a
              href="/auth/login"
              className="text-gray-300 hover:bg-gray-200 hover:text-gray-800 rounded-md px-3 py-2 text-sm font-medium"
              >Login</a>)}
            <LogoutUser />
            </div>
            <div className="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
              <div className="relative ml-3">
                <div>
                  <button
                    type="button"
                    className="relative flex rounded-full bg-gray-200 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-200"
                    id="user-menu-button"
                    aria-expanded="false"
                    aria-haspopup="true"
                  ></button>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="sm:hidden" id="mobile-menu">
          <div className="space-y-1 px-2 pb-3 pt-2">
            <a
              href="#"
              className="bg-gray-200 text-gray-800 block rounded-md px-3 py-2 text-base font-medium"
              aria-current="page"
            >
              Dashboard
            </a>
            <a
              href="#"
              className="text-gray-300 hover:bg-gray-200 hover:text-gray-800 block rounded-md px-3 py-2 text-base font-medium"
            >
              Team
            </a>
            <a
              href="#"
              className="text-gray-300 hover:bg-gray-200 hover:text-gray-800 block rounded-md px-3 py-2 text-base font-medium"
            >
              Projects
            </a>
            <a
              href="#"
              className="text-gray-300 hover:bg-gray-200 hover:text-gray-800 block rounded-md px-3 py-2 text-base font-medium"
            >
              Calendar
            </a>
            <LoginDialogMobile />
          </div>
        </div>
      </nav>
      {children}
    </html>
  );
  */

  return (
    <div className="flex min-h-screen w-full flex-col">
      <CommandDialog open={open} onOpenChange={setOpen}>
        <CommandInput placeholder="Type a command or search..." />
        <CommandList>
          <CommandEmpty>No results found.</CommandEmpty>
          <CommandGroup heading="Suggestions">
            <CommandItem>Calendar</CommandItem>
            <CommandItem>Search Emoji</CommandItem>
            <CommandItem>Calculator</CommandItem>
          </CommandGroup>
        </CommandList>
      </CommandDialog>
      <header className="sticky top-0 flex h-16 items-center gap-4 border-b bg-background px-4 md:px-6">
        <nav className="hidden flex-col gap-6 text-lg font-medium md:flex md:flex-row md:items-center md:gap-5 md:text-sm lg:gap-6">
          <Link
            href="/"
            className="flex items-center gap-2 text-lg font-semibold md:text-base"
          >
            <Package2 className="h-6 w-6" />
            <span className="sr-only">Acme Inc</span>
          </Link>
          <Button variant="link">
            <Link href="/docs">Explore Datasets</Link>
          </Button>
          <Button variant="link">
            <Link href="/docs">Documentation</Link>
          </Button>
          <Link
            href="/docs"
            className="text-muted-foreground transition-colors hover:text-foreground gap-3 rounded-lg bg-muted px-3 py-2 text-primary"
          >
            Documentation
          </Link>
          <Link
            href="/discuss"
            className="text-muted-foreground transition-colors hover:text-foreground"
          >
            Discuss
          </Link>
          <Link
            href="#"
            className="text-muted-foreground transition-colors hover:text-foreground"
          >
            Customers
          </Link>
          <Link
            href="#"
            className="text-foreground transition-colors hover:text-foreground"
          >
            Settings
          </Link>
        </nav>
        <Sheet>
          <SheetTrigger asChild>
            <Button
              variant="outline"
              size="icon"
              className="shrink-0 md:hidden"
            >
              <Menu className="h-5 w-5" />
              <span className="sr-only">Toggle navigation menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="left">
            <nav className="grid gap-6 text-lg font-medium">
              <Link
                href="#"
                className="flex items-center gap-2 text-lg font-semibold"
              >
                <Package2 className="h-6 w-6" />
                <span className="sr-only">Acme Inc</span>
              </Link>
              <Link
                href="#"
                className="text-muted-foreground hover:text-foreground"
              >
                Dashboard
              </Link>
              <Link
                href="#"
                className="text-muted-foreground hover:text-foreground"
              >
                Orders
              </Link>
              <Link
                href="#"
                className="text-muted-foreground hover:text-foreground"
              >
                Products
              </Link>
              <Link
                href="#"
                className="text-muted-foreground hover:text-foreground"
              >
                Customers
              </Link>
              <Link href="#" className="hover:text-foreground">
                Settings
              </Link>
            </nav>
          </SheetContent>
        </Sheet>
        <div className="flex w-full items-center gap-4 md:ml-auto md:gap-2 lg:gap-4">
          <div className="ml-auto flex-1 sm:flex-initial">
            <Button style={{ marginRight: "10px" }} variant="ghost">
              <Link href="/auth/login" className="text-muted-foreground">
                Login
              </Link>
            </Button>
            <Button variant="outline">
              <Link href="/auth/signup" className="text-muted-foreground">
                Signup
              </Link>
            </Button>
          </div>
        </div>
      </header>
      {children}
    </div>
  );
}
