import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import { cn } from "@/lib/utils";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

import { LoginDialogDesktop } from "@/components/auth/loginDialogDesktop";
import { LoginDialogMobile } from "@/components/auth/loginDialogMobile";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dataset Colab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <nav className="bg-white">
        <div className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
          <div className="relative flex h-16 items-center justify-between">
            <div className="absolute inset-y-0 left-0 flex items-center sm:hidden">
              <button
                type="button"
                className="relative inline-flex items-center justify-center rounded-md p-2 text-gray-800 hover:bg-gray-200 hover:text-gray-800 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
                aria-controls="mobile-menu"
                aria-expanded="false"
              ></button>
            </div>
            <div className="flex flex-1 items-center justify-between sm:items-stretch sm:justify-start">
              <div className="flex flex-shrink-0 items-center">
                <h1 className="pr-3" style={{ whiteSpace: "nowrap" }}>
                  Dataset Colab
                </h1>
                <a
                  href="#"
                  className="text-gray-300 hover:bg-gray-200 hover:text-gray-800 rounded-md px-3 py-2 text-sm font-medium"
                >
                  Explore Datasets
                </a>
              </div>
              <div className="hidden sm:flex sm:ml-auto">
                <div className="flex space-x-4"></div>
                <div className="flex space-x-4 ml-auto">
                  <div className="flex w-full max-w-sm items-center space-x-2">
                    <Input placeholder="Search..." />
                    <Button type="submit">Search</Button>
                  </div>
                </div>
                <div className="ml-4"></div>
              </div>
              <a
                href="/auth/login"
                className="text-gray-300 hover:bg-gray-200 hover:text-gray-800 rounded-md px-3 py-2 text-sm font-medium"
              >
                Login
              </a>
            </div>
            <div className="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
              <div className="relative ml-3">
                <div>
                  <button
                    type="button"
                    className="relative flex rounded-full bg-gray-200 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-200"
                    id="user-menu-button"
                    aria-expanded="false"
                    aria-haspopup="true"
                  ></button>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="sm:hidden" id="mobile-menu">
          <div className="space-y-1 px-2 pb-3 pt-2">
            <a
              href="#"
              className="bg-gray-200 text-gray-800 block rounded-md px-3 py-2 text-base font-medium"
              aria-current="page"
            >
              Dashboard
            </a>
            <a
              href="#"
              className="text-gray-300 hover:bg-gray-200 hover:text-gray-800 block rounded-md px-3 py-2 text-base font-medium"
            >
              Team
            </a>
            <a
              href="#"
              className="text-gray-300 hover:bg-gray-200 hover:text-gray-800 block rounded-md px-3 py-2 text-base font-medium"
            >
              Projects
            </a>
            <a
              href="#"
              className="text-gray-300 hover:bg-gray-200 hover:text-gray-800 block rounded-md px-3 py-2 text-base font-medium"
            >
              Calendar
            </a>
            <LoginDialogMobile />
          </div>
        </div>
      </nav>
      {children}
    </html>
  );
}
